# Generated by Django 5.2.4 on 2026-02-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='profile_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
