# Generated by Django 5.2.4 on 2026-03-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_signin_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='user_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
