# Generated by Django 5.2.4 on 2026-03-01 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_signin_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_photo', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('city', models.CharField(blank=True, max_length=50)),
                ('language', models.CharField(blank=True, max_length=20)),
                ('experience', models.IntegerField(default=0)),
                ('skills', models.TextField(blank=True)),
                ('portfolio', models.TextField(blank=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('about', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
