# Generated by Django 5.2.4 on 2026-03-02 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_seller_profile_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('search_tag', models.CharField(max_length=100)),
                ('work_type', models.CharField(max_length=100)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('portfolio_image', models.ImageField(blank=True, null=True, upload_to='proposals/images/')),
                ('doc_portfolio', models.FileField(blank=True, null=True, upload_to='proposals/docs/')),
                ('video_intro', models.FileField(blank=True, null=True, upload_to='proposals/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='myapp.seller_profile')),
            ],
        ),
    ]
