# Generated by Django 5.2.4 on 2026-03-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='delivery_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proposal',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
