# Generated by Django 5.2.4 on 2026-03-03 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_proposal_delivery_time_proposal_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalImpression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='myapp.proposal')),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
