# Generated by Django 5.2.4 on 2026-03-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_profile',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
    ]
