# Generated by Django 5.2.4 on 2026-03-15 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_seller_profile_avg_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='signin',
            name='email_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signin',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
