# Generated by Django 5.2.4 on 2026-03-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_signin_email_otp_signin_email_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signin',
            name='is_phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
