# Generated by Django 5.2.4 on 2026-03-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_signin_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_profile',
            name='area',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
